version: 2
updates:
- package-ecosystem: pip
  directory: "/back"
  schedule:
    interval: daily
    time: "04:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: spotipy
    versions:
    - 2.16.1
    - 2.17.1
